---
# NOTE:
# - ec2_key_name is passed with include
# - vpc comes from upper scope

- name: "{{ ec2_key_name }} > ec2 ssh key"
  block:
  - name: "{{ ec2_key_name }} > create ec2 ssh key"
    ec2_key:
      state: present
      name: "{{ ec2_key_name }}"
      region: "{{ vpc.region }}"
    register: ec2_key_output

  - name: "{{ ec2_key_name }} > create .ssh/{{ vpc.market }} directory"
    file:
      path: "../.ssh/{{ vpc.market }}"
      state: directory
    when: ec2_key_output is changed

  - name: "{{ ec2_key_name }} > save ./.ssh/{{ vpc.market }}/{{ ec2_key_name }}.pem"
    copy:
      content: "{{ ec2_key_output.key.private_key }}"
      dest: "../.ssh/{{ vpc.market }}/{{ ec2_key_name }}.pem"
      mode: 0600
    when: ec2_key_output is changed

  tags:
  - vpc-ec2-keys
