---
# NOTE:
# - kms_key Dict is passed with include
# - vpc Dict comes from upper scope

- name: "{{ kms_key.name }} > kms key"
  block:
  - name: "{{ kms_key.name }} > assert config"
    assert:
      that:
      - kms_key.name is string
      - kms_key.name | length > 0
      msg: KMS key is misconfigured.

  - name: "{{ kms_key.name }} > create kms key"
    aws_kms:
      alias: "{{ kms_key.name }}"
      region: "{{ vpc.region }}"
      tags: >
        {{
          kms_key.tags | d({})
            | combine(vpc.tags)
            | combine({'Name': kms_key.name})
        }}

  tags:
  - vpc-kms-keys
