---
- name: assert configs
  assert:
    that:
    - aws_lm_vpc.region is string
    - aws_lm_vpc.region | length > 0
    - aws_lm_vpc.name is string
    - aws_lm_vpc.name | length > 0
    - aws_lm_srv is sequence
    - aws_lm_srv | length > 0
    msg: Lambda is misconfigured.
  tags:
  - always


- name: fetch vpc info
  ec2_vpc_net_info:
    region: "{{ aws_lm_vpc.region }}"
    filters:
      "tag:Name": "{{ aws_lm_vpc.name }}"
  register: vpc_info_output

- name: set lm vpc id
  set_fact:
    set_lm_vpc_id: "{{ vpc_info_output.vpcs[0].vpc_id }}"


- include_tasks: lambda.yml
  loop: "{{ aws_lm_srv }}"  # List[Dict]
  loop_control:
    loop_var: aws_lm


- name: unset local vars
  set_fact:
    vpc_info_output: null
    set_lm_vpc_id: null
