---
# - iam_user is passed with include

- name: assert iam user config
  assert:
    that:
    - iam_user is mapping
    - iam_user.name is string
    - iam_user.name | length > 0
    msg: IAM user is misconfigured.


- name: "{{ iam_user.name }} > set user defaults"
  set_fact:
    set_user: "{{
      aws_iam_user_default | combine(iam_user, recursive=True)
    }}"  # Dict


- name: "{{ set_user.name }} > manage iam user"
  iam_user:
    state: "{{ set_user.state }}"
    region: "{{ set_user.region }}"
    name: "{{ set_user.name }}"
    managed_policy: "{{ set_user.policies }}"
  async: 20
  poll: 0
  register: async_output
  changed_when: False
  when: not set_user.name.startswith('arn:aws:')


- name: "{{ set_user.name }} > warning"
  debug:
    msg: >-
      IAM user name defined as ARN is assumed to belong to a foreign
      AWS account, therefore is not managed locally.
  when: set_user.name.startswith('arn:aws:')


- name: "{{ set_user.name }} > append async results list"
  set_fact:
    async_output_results: "{{ async_output_results + [async_output | d({})] }}"
